--
-- Table structure for table `dbBrainBuildersRegistrationForm`
--
CREATE TABLE `dbBrainBuildersRegistrationForm` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `child_first_name` VARCHAR(50) NOT NULL,
    `child_last_name` VARCHAR(50) NOT NULL,
    `gender` VARCHAR(6) NOT NULL,
    `school_name` VARCHAR(100) NOT NULL,
    `grade` VARCHAR(20) NOT NULL,
    `birthdate` DATE NOT NULL,
    `child_address` VARCHAR(100) NOT NULL,
    `child_city` VARCHAR(50) NOT NULL,
    `child_state` CHAR(2) NOT NULL,
    `child_zip` CHAR(5) NOT NULL,
    `child_medical_allergies` VARCHAR(255),
    `child_food_avoidances` VARCHAR(255),
    `parent1_name` VARCHAR(100) NOT NULL,
    `parent1_phone` CHAR(14) NOT NULL,
    `parent1_address` VARCHAR(100) NOT NULL,
    `parent1_city` VARCHAR(50) NOT NULL,
    `parent1_state` CHAR(2) NOT NULL,
    `parent1_zip` CHAR(5) NOT NULL,
    `parent1_email` VARCHAR(100) NOT NULL,
    `parent1_altPhone` CHAR(14) NOT NULL,
    `parent2_name` VARCHAR(100),
    `parent2_phone` CHAR(14),
    `parent2_address` VARCHAR(100),
    `parent2_city` VARCHAR(50),
    `parent2_state` CHAR(2),
    `parent2_zip` CHAR(5),
    `parent2_email` VARCHAR(100),
    `parent2_altPhone` CHAR(14),
    `emergency_name1` VARCHAR(100) NOT NULL,
    `emergency_relationship1` VARCHAR(50) NOT NULL,
    `emergency_phone1` CHAR(14) NOT NULL,
    `emergency_name2` VARCHAR(100),
    `emergency_relationship2` VARCHAR(50),
    `emergency_phone2` CHAR(14),
    `authorized_pu` VARCHAR(255) NOT NULL,
    `not_authorized_pu` VARCHAR(255),
    `primary_language` VARCHAR(50) NOT NULL, 
    `hispanic_latino_spanish` ENUM('yes', 'no') NOT NULL,
    `race` ENUM('Caucasian', 'Black/African American', 'Native Indian/Alaska Native', 'Native Hawaiian/Pacific Islander', 'Asian', 'Multiracial', 'Other') NOT NULL,
    `num_unemployed` INT,
    `num_retired` INT,
    `num_unemployed_student` INT,
    `num_employed_fulltime` INT,
    `num_employed_parttime` INT,
    `num_employed_student` INT,
    `income` VARCHAR(20) NOT NULL,
    `other_programs` VARCHAR(255),
    `lunch` ENUM('free', 'reduced', 'neither') NOT NULL,
    `needs_transportation` ENUM('needs-transportation', 'transports-themselves') NOT NULL,
    `participation` ENUM('yes', 'no') NOT NULL,
    `parent_initials` VARCHAR(10) NOT NULL,
    `signature` VARCHAR(100) NOT NULL,
    `signature_date` DATE NOT NULL,
    `waiver_child_name` VARCHAR(100) NOT NULL,
    `waiver_dob` DATE NOT NULL,
    `waiver_parent_name` VARCHAR(100) NOT NULL,
    `waiver_provider_name` VARCHAR(100) NOT NULL,
    `waiver_provider_address` VARCHAR(255) NOT NULL,
    `waiver_phone_and_fax` VARCHAR(50) NOT NULL,
    `waiver_signature` VARCHAR(100) NOT NULL,
    `waiver_date` DATE NOT NULL
);
